### ISSUE TITLE
Installation failing

### ISSUE THREAD

**Issue by markfeinstein** [camdencheek/tree-sitter-go-mod#10]
I'm trying to do a fresh install of the plugin and seeing the bellow error. Looking at the contents of the filesystem I'm seeing a discrepancy between the file structure on disk and what is expected by the installation process. I have `tree-sitter-gomod-4a65743dbc2bb3094114dd2b43da03c820aa5234` but the process is trying to rename `tree-sitter-go-mod-4a65743dbc2bb3094114dd2b43da03c820aa5234` 
```
nvim-treesitter[gomod]: Failed to execute the following command:
{
  cmd = "mv",
  opts = {
    args = { "-f", "tree-sitter-gomod-tmp/tree-sitter-go-mod-4a65743dbc2bb3094114dd2b43da03c820aa5234", "tree-sitter-gomod" },
    cwd = "/Users/mark/.local/share/nvim",
    stdio = {
      [2] = <userdata 1>,
      [3] = <userdata 2>
    }
  }
}
mv: rename tree-sitter-gomod-tmp/tree-sitter-go-mod-4a65743dbc2bb3094114dd2b43da03c820aa5234 to tree-sitter-gomod: No such file or directory
```

**Comment by camdencheek** [comment]
Hey! Thanks for the report. I had [changed the name of the repo](https://github.com/camdencheek/tree-sitter-go-mod/issues/9) for consistency with the module name, but it seems `nvim-treesitter` does not successfully follow the redirect. I've reverted the name change, and installing locally works for me again

**Comment by ryandesign** [comment]
It's not about following redirects; that works fine. It's about the fact that GitHub's automatically-generated tarballs contain the repository name in the enclosing directory name. If you change the repository name, that messes up build scripts that were expecting a particular enclosing directory name, as was the case here, and anyone who was checking the checksums of those automatically-generated tarballs, as was the case in MacPorts: https://trac.macports.org/ticket/68105

**Comment by ryandesign** [comment]
You avoid these problems in the future by publishing manually-generated tarballs (which you can upload to your GitHub releases) so that users don't have to rely on automatically-generated tarballs, which have been the subject of other [unexpected changes](https://lists.macports.org/pipermail/macports-dev/2023-February/044930.html) before.
