### ISSUE TITLE
I have gomod installed in Treesitter but still highlighting not working

### ISSUE THREAD

**Issue by khanakia** [camdencheek/tree-sitter-go-mod#13]
This is how it looks just plain text. 
File should have syntax hightlights

![Screenshot 2024-01-09 at 5 35 20 PM](https://github.com/camdencheek/tree-sitter-go-mod/assets/2174170/eaa6db5c-38b0-4842-9a65-706972f83695)

**Comment by camdencheek** [comment]
Hi @khanakia! This is almost definitely not an issue with `tree-sitter-go-mod`, so I won't be able to help ya much. 

A few places to start looking:
- Does treesitter highlighting work for other languages?
- What is the output of `:set ft`? It should be `filetype=gomod`
- Does `:TSModuleInfo` show that gomod is installed? Are highlights shown as active?

Good luck!

**Comment by khanakia** [comment]
I believe it's an issue with filetype any idea how I can fix this ?

1. Yes Treesitter works correct with go or js files
2. it shows the file type to `filetype=rapid`
3. Check screenshot please it's correctly installed

![Screenshot 2024-01-09 at 9 38 59 PM](https://github.com/camdencheek/tree-sitter-go-mod/assets/2174170/ddbe7687-e7d4-4a43-ac47-f11b87b64e2b)

**Comment by khanakia** [comment]
@camdencheek neovim just closed the issue without giving any proper reason

**Comment by camdencheek** [comment]
Looks like the removed filtetype detection. TIL! Anyways, something like [this](https://stackoverflow.com/questions/11666170/persistent-set-syntax-for-a-given-filetype) should still work for you.
