### ISSUE TITLE
Change repository url in `Cargo.toml`

### ISSUE THREAD

**Issue by ever0de** [camdencheek/tree-sitter-go-mod#14]
https://github.com/camdencheek/tree-sitter-go-mod/blob/9b86399ab733fbd548ba0e817e732cb3351082d2/Cargo.toml#L7

maybe <https://github.com/tree-sitter/tree-sitter-go-mod> -> <https://github.com/camdencheek/tree-sitter-go-mod> ?

**Comment by camdencheek** [comment]
Do'h. Fixed! Thanks 🙂
